// Recursos de Accesibilidad
const ladescripcion = "Este espacio cuenta con los siguientes recursos de accesibilidad";
const larampa = "Rampas";
const elascensor = "Ascensores";
const lasentradas = "Entradas y Puertas Accesibles";
const losbanos = "Baños Accesibles";
const lasenalizacion = "Señalización Clara y Accesible";
const lospuntos = "Puntos de Información Accesible";
const elmobiliario = "Mobiliario Adaptado";
const elestacionamiento = "Estacionamiento para Personas con Discapacidad";


//Datos del array para cargar en el modal al hacer clic en el marcador
const datos = [
    {   
        id: 1, 
        nombre: [true, "Escuela de Arquitectura"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 2, 
        nombre: [true, "Taller Arquitectura (Galpón Herramientas)"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 3, 
        nombre: [true, "Instituto (Lab.) Matemáticas y Física+DAES"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 4, 
        nombre: [true, "Instituto de Matemáticas, Taller, Otros"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 5, 
        nombre: [true, "Instituto Química y Recursos Naturales  "],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 6, 
        nombre: [true, "Escuela de Música"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 7, 
        nombre: [true, "Salón Diego Portales"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 8, 
        nombre: [true, "Administración de Campus"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 9, 
        nombre: [true, "Edificio Institutos Idiomas, Humanidades y Matemáticas"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 10, 
        nombre: [true, "Gimnasio 1"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 11, 
        nombre: [true, "Sala de Máquinas"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 12, 
        nombre: [true, "Ex Aulas 100 /Escuela de Video Juegos"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 13, 
        nombre: [true, "Escuela de Bioinformática "],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 14, 
        nombre: [true, "Edificio Prosperidad II"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 15, 
        nombre: [true, "Edificio Video Juegos, IIDE, Salud Pública"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 16, 
        nombre: [true, "Edificio Manuel Toso (Aulas 200)"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 17, 
        nombre: [true, "Escuela de Diseño"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa],
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 18, 
        nombre: [true, "Vicerrectoría de Formación"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 19, 
        nombre: [true, "Gestión Curricular"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 20, 
        nombre: [true, "Salas de Tutorías, Vicerrectoría de Pregrado (PACE/SIBERIA)"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 21, 
        nombre: [true, "Kiosco Norte (Dolape)"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 22, 
        nombre: [true, "Comedor Funcionarios y Sala Ecuménica (Cefetería El Establo)"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 23, 
        nombre: [true, "Escuelas de Kinesiología y Fonoaudiología"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 24, 
        nombre: [true, "Aulas 700 / Neurociencias"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 25, 
        nombre: [true, "Fac. de Ciencias Jurídicas"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 26, 
        nombre: [true, "Dirección Tecnología de la Información (DTI)"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 27, 
        nombre: [true, "Nutrición y Dietética"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 28, 
        nombre: [true, "CEAP Centro de Estudios en Alimentos"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 29, 
        nombre: [true, "Casino"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 30, 
        nombre: [true, "Biblioteca Central"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 31, 
        nombre: [true, "Vicerrectoría de Servicios Estudiantiles (VDE)"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 32, 
        nombre: [true, "Laboratorio de Inocuidad Alimentaria"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 33, 
        nombre: [true, "Laboratorios de Fenómica Vegetal"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 34, 
        nombre: [true, "Instituto de Química y CICA"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 35, 
        nombre: [true, "Módulo Sala de Clases 1  Quillay"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 36, 
        nombre: [true, "Aulas 600"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 37, 
        nombre: [true, "Cafetería (Barcelona)"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 38, 
        nombre: [true, "Vicerrectoría Académica"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 39, 
        nombre: [true, "Centro Tecnológico de Geomática"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 40, 
        nombre: [true, "Centro Tecnológico de Riego "],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 41, 
        nombre: [true, "Centro Tecnológico de Riego "],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 42, 
        nombre: [true, "Centros Tecnológico de Pomáceas"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 43, 
        nombre: [true, "Facultad de Ciencias Agrarias"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 44, 
        nombre: [true, "Bodega  de Microvinificación"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 45, 
        nombre: [true, "Instituto de Ciencias Biológicas"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 46, 
        nombre: [true, "Edificio Prosperidad II (Salas 500)"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 47, 
        nombre: [true, "Kiosko Naturista (Dragón Verde)"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 48, 
        nombre: [true, "Facultad de Odontología"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 49, 
        nombre: [true, "Edificio Terapia Ocupacional"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 50, 
        nombre: [true, "Edificio Laboratorios Tecnología Médica"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 51, 
        nombre: [true, "Edificio Bicentenario"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 52, 
        nombre: [true, "Compl. Tecnológico de Autoaprendizaje"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 53, 
        nombre: [true, "Facultad de Psicología"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 54, 
        nombre: [true, "Facultad de Economía y Negocios FEN"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 55, 
        nombre: [true, "Clínicas Kinesiología y Fonoaudiología"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 56, 
        nombre: [true, "Aulas 800"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 57, 
        nombre: [true, "Laboratorios de Docencia del Instituto de Ciencias Biológicas"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 58, 
        nombre: [true, "Dirección de Comunicaciones"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 59, 
        nombre: [true, "Clínicas Odontológicas"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 60, 
        nombre: [true, "Laboratorio Control Motor Humano"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [false, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 61, 
        nombre: [true, "Módulo Sala de Clases 2 - Arrayán"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [false, elestacionamiento]
    },
    {   
        id: 62, 
        nombre: [true, "Galería de Exposición Pequeño Formato"],
        descripcion: [true, ladescripcion],
        rampa: [false, larampa], 
        ascensores: [false, elascensor],
        entradas: [false, lasentradas], 
        banos: [false, losbanos],
        senalizacion: [false, lasenalizacion],
        puntoinfo: [false, lospuntos],
        mobiliario: [false, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 63, 
        nombre: [true, "Banco Santander"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    },
    {   
        id: 67, 
        nombre: [true, "Ciencias Básicas Biomédicas"],
        descripcion: [true, ladescripcion],
        rampa: [true, larampa], 
        ascensores: [true, elascensor],
        entradas: [true, lasentradas], 
        banos: [true, losbanos],
        senalizacion: [true, lasenalizacion],
        puntoinfo: [true, lospuntos],
        mobiliario: [true, elmobiliario],
        estacionamiento: [true, elestacionamiento]
    }

]